#undef runtracmass
#define periodic_ew
#undef periodic_ns
#undef allow_particle
#define rhoonly
#undef relaxation
#undef fixed_bottom_thickness
#define gotm_call
#define file_output
#define file_output_cdf
#define file_output_bin
